import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ProgramType, ProgramTemplate, GameFunction, AVAILABLE_FUNCTIONS, PROGRAM_BASE_STATS, getNextVersion } from '../types/GameTypes';
import { X, Plus, Trash2, Save } from 'lucide-react';
interface ProgramTemplateCreatorProps {
  baseTemplate?: ProgramTemplate;
  existingTemplates: ProgramTemplate[];
  onSave: (template: Omit<ProgramTemplate, 'id' | 'owner' | 'createdAt'>) => void;
  onClose: () => void;
}
export function ProgramTemplateCreator({
  baseTemplate,
  existingTemplates,
  onSave,
  onClose
}: ProgramTemplateCreatorProps) {
  const [type, setType] = useState<ProgramType>(baseTemplate?.type || 'offensive');
  const [selectedFunctions, setSelectedFunctions] = useState<GameFunction[]>(baseTemplate?.functions || []);
  const [selectedCategory, setSelectedCategory] = useState<'all' | 'generic' | 'attack' | 'defense' | 'trace'>('all');
  const [autoGeneratedName, setAutoGeneratedName] = useState('');
  const baseStats = PROGRAM_BASE_STATS[type];
  // Calculate version based on existing templates and changes
  const getVersion = (): string => {
    if (baseTemplate) {
      // Versioning existing template
      if (selectedFunctions.length > baseTemplate.functions.length) {
        return getNextVersion(baseTemplate.version, 'minor');
      }
      const functionsChanged = selectedFunctions.some((f, i) => !baseTemplate.functions[i] || f.id !== baseTemplate.functions[i].id);
      if (functionsChanged) {
        return getNextVersion(baseTemplate.version, 'patch');
      }
      return baseTemplate.version;
    } else {
      // Creating new template - find highest version for this type
      const templatesOfType = existingTemplates.filter(t => t.type === type && t.owner === 'playerA');
      if (templatesOfType.length === 0) {
        return '1.0.0';
      }
      // Find the highest version
      const versions = templatesOfType.map(t => {
        const [major, minor, patch] = t.version.split('.').map(Number);
        return {
          major,
          minor,
          patch,
          full: t.version
        };
      });
      versions.sort((a, b) => {
        if (a.major !== b.major) return b.major - a.major;
        if (a.minor !== b.minor) return b.minor - a.minor;
        return b.patch - a.patch;
      });
      const highestVersion = versions[0].full;
      // If no functions, increment patch; if functions added, increment minor
      if (selectedFunctions.length === 0) {
        return getNextVersion(highestVersion, 'patch');
      } else {
        return getNextVersion(highestVersion, 'minor');
      }
    }
  };
  // Update auto-generated name whenever type or functions change
  useEffect(() => {
    const version = getVersion();
    const capitalizedType = type.charAt(0).toUpperCase() + type.slice(1);
    setAutoGeneratedName(`${capitalizedType} v${version}`);
  }, [type, selectedFunctions, baseTemplate, existingTemplates]);
  // Filter functions based on program type
  const getAvailableFunctionsForType = (): GameFunction[] => {
    return AVAILABLE_FUNCTIONS.filter(func => {
      if (func.category === 'generic') return true;
      if (type === 'offensive' && func.category === 'attack') return true;
      if (type === 'defensive' && func.category === 'defense') return true;
      if (type === 'trace' && func.category === 'trace') return true;
      return false;
    });
  };
  const availableFunctionsForType = getAvailableFunctionsForType();
  const availableFunctions = availableFunctionsForType.filter(func => {
    if (selectedCategory === 'all') return true;
    return func.category === selectedCategory;
  });
  const getValidCategories = (): Array<'all' | 'generic' | 'attack' | 'defense' | 'trace'> => {
    const categories: Array<'all' | 'generic' | 'attack' | 'defense' | 'trace'> = ['all', 'generic'];
    if (type === 'offensive') categories.push('attack');
    if (type === 'defensive') categories.push('defense');
    if (type === 'trace') categories.push('trace');
    return categories;
  };
  const validCategories = getValidCategories();
  const handleAddFunction = (func: GameFunction) => {
    if (!selectedFunctions.find(f => f.id === func.id)) {
      setSelectedFunctions([...selectedFunctions, func]);
    }
  };
  const handleRemoveFunction = (funcId: string) => {
    setSelectedFunctions(selectedFunctions.filter(f => f.id !== funcId));
  };
  const handleSave = () => {
    const template: Omit<ProgramTemplate, 'id' | 'owner' | 'createdAt'> = {
      name: autoGeneratedName,
      type,
      version: getVersion(),
      baseStats,
      functions: selectedFunctions
    };
    onSave(template);
  };
  const getModifiedStats = () => {
    let stats = {
      ...baseStats
    };
    selectedFunctions.forEach(func => {
      if (func.effect.type === 'stat_boost' && func.effect.stat && func.effect.value) {
        stats[func.effect.stat] += func.effect.value;
      }
    });
    return stats;
  };
  const modifiedStats = getModifiedStats();
  return <motion.div initial={{
    opacity: 0
  }} animate={{
    opacity: 1
  }} exit={{
    opacity: 0
  }} className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm" onClick={onClose}>
      <motion.div initial={{
      scale: 0.9,
      opacity: 0
    }} animate={{
      scale: 1,
      opacity: 1
    }} exit={{
      scale: 0.9,
      opacity: 0
    }} onClick={e => e.stopPropagation()} className="bg-black border-4 border-[#00ff00] rounded-lg p-6 max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-[0_0_40px_#00ff00]">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-2xl font-bold text-[#00ff00] font-mono">
            {baseTemplate ? 'VERSION_PROGRAM' : 'CREATE_PROGRAM'}
          </h2>
          <button onClick={onClose} className="text-[#00ff00] hover:text-white p-2 hover:bg-[#00ff00]/20 rounded transition-colors">
            <X size={24} />
          </button>
        </div>

        {/* Program Type Selection */}
        <div className="mb-6">
          <label className="block text-sm font-bold text-[#00ff00] mb-2 font-mono">
            BASE_TYPE:
          </label>
          <select value={type} onChange={e => {
          const newType = e.target.value as ProgramType;
          setType(newType);
          setSelectedFunctions(prev => prev.filter(f => f.category === 'generic' || newType === 'offensive' && f.category === 'attack' || newType === 'defensive' && f.category === 'defense' || newType === 'trace' && f.category === 'trace'));
        }} disabled={!!baseTemplate} className="w-full px-3 py-2 bg-black border-2 border-[#00ff00] rounded text-[#00ff00] font-mono focus:outline-none focus:shadow-[0_0_10px_#00ff00] disabled:opacity-50">
            <option value="offensive">Offensive</option>
            <option value="defensive">Defensive</option>
            <option value="trace">Trace</option>
          </select>
        </div>

        {/* Auto-generated Program Name (Display Only) */}
        <div className="mb-6">
          <label className="block text-sm font-bold text-[#00ff00] mb-2 font-mono">
            PROGRAM_NAME:{' '}
            <span className="text-xs text-[#00ff00]/60">(auto-generated)</span>
          </label>
          <div className="w-full px-3 py-2 bg-black/50 border-2 border-[#00ff00]/50 rounded text-[#00ff00] font-mono">
            {autoGeneratedName || 'Calculating...'}
          </div>
        </div>

        {/* Type Restriction Notice */}
        <div className="mb-6 p-3 bg-[#00ff00]/10 border border-[#00ff00] rounded">
          <p className="text-xs text-[#00ff00]/80 font-mono">
            ℹ️ {type.toUpperCase()} programs can use GENERIC and{' '}
            {type.toUpperCase()}-specific functions only
          </p>
        </div>

        {/* Stats Preview */}
        <div className="mb-6 p-4 bg-[#00ff00]/10 border-2 border-[#00ff00] rounded">
          <div className="flex items-center justify-between mb-3">
            <h3 className="font-bold text-[#00ff00] font-mono">
              STATS_PREVIEW:
            </h3>
            <span className="text-sm font-mono text-[#00ff00]">
              VERSION: {getVersion()}
            </span>
          </div>
          <div className="grid grid-cols-4 gap-4 text-sm font-mono">
            <div>
              <span className="text-[#00ff00]/70">ENERGY:</span>
              <span className="ml-2 font-bold text-[#00ff00]">
                {modifiedStats.energy}
              </span>
            </div>
            <div>
              <span className="text-[#00ff00]/70">ATTACK:</span>
              <span className="ml-2 font-bold text-[#00ff00]">
                {modifiedStats.attack}
              </span>
            </div>
            <div>
              <span className="text-[#00ff00]/70">DEFENSE:</span>
              <span className="ml-2 font-bold text-[#00ff00]">
                {modifiedStats.defense}
              </span>
            </div>
            <div>
              <span className="text-[#00ff00]/70">MOVEMENT:</span>
              <span className="ml-2 font-bold text-[#00ff00]">
                {modifiedStats.movement}
              </span>
            </div>
          </div>
        </div>

        {/* Selected Functions */}
        {selectedFunctions.length > 0 && <div className="mb-6">
            <h3 className="font-bold text-[#00ff00] mb-2 font-mono">
              INSTALLED_FUNCTIONS: ({selectedFunctions.length})
            </h3>
            <div className="space-y-2">
              {selectedFunctions.map(func => <div key={func.id} className="flex items-center justify-between p-3 bg-[#00ff00]/10 border border-[#00ff00] rounded">
                  <div className="flex-1">
                    <div className="font-bold text-[#00ff00] font-mono text-sm">
                      {func.name}
                    </div>
                    <div className="text-xs text-[#00ff00]/70 font-mono">
                      {func.description}
                    </div>
                  </div>
                  <button onClick={() => handleRemoveFunction(func.id)} className="ml-3 p-2 text-red-400 hover:bg-red-900/40 rounded transition-colors">
                    <Trash2 size={16} />
                  </button>
                </div>)}
            </div>
          </div>}

        {/* Function Library */}
        <div>
          <h3 className="font-bold text-[#00ff00] mb-3 font-mono">
            FUNCTION_LIBRARY:
          </h3>

          {/* Category Filter */}
          <div className="flex gap-2 mb-4 flex-wrap">
            {validCategories.map(cat => <button key={cat} onClick={() => setSelectedCategory(cat)} className={`px-3 py-1 rounded font-mono text-xs transition-all ${selectedCategory === cat ? 'bg-[#00ff00] text-black shadow-[0_0_10px_#00ff00]' : 'bg-black/60 text-[#00ff00] border border-[#00ff00] hover:bg-[#00ff00]/20'}`}>
                {cat.toUpperCase()}
              </button>)}
          </div>

          {/* Function List */}
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {availableFunctions.length === 0 ? <div className="text-center py-8 text-[#00ff00]/60 font-mono text-sm">
                No functions available in this category
              </div> : availableFunctions.map(func => {
            const alreadyHas = selectedFunctions.some(f => f.id === func.id);
            return <div key={func.id} className={`p-3 rounded border transition-all ${alreadyHas ? 'bg-[#00ff00]/20 border-[#00ff00] opacity-50' : 'bg-black/60 border-[#00ff00] hover:bg-[#00ff00]/10'}`}>
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <h4 className="font-bold text-[#00ff00] font-mono text-sm">
                            {func.name}
                          </h4>
                          <span className="text-xs px-2 py-0.5 bg-[#00ff00]/20 text-[#00ff00] rounded font-mono">
                            {func.category.toUpperCase()}
                          </span>
                        </div>
                        <p className="text-xs text-[#00ff00]/80 font-mono">
                          {func.description}
                        </p>
                      </div>
                      <button onClick={() => handleAddFunction(func)} disabled={alreadyHas} className="ml-3 p-2 bg-[#00ff00] text-black hover:bg-[#00cc00] disabled:bg-gray-700 disabled:text-gray-500 disabled:opacity-50 rounded transition-colors">
                        <Plus size={16} />
                      </button>
                    </div>
                  </div>;
          })}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-3 mt-6">
          <button onClick={handleSave} className="flex-1 py-3 bg-[#00ff00] text-black hover:bg-[#00cc00] rounded-lg font-bold transition-colors font-mono flex items-center justify-center gap-2 shadow-[0_0_20px_#00ff00]">
            <Save size={20} />
            SAVE_PROGRAM
          </button>
          <button onClick={onClose} className="px-6 py-3 bg-black border-2 border-[#00ff00] text-[#00ff00] hover:bg-[#00ff00]/20 rounded-lg font-bold transition-colors font-mono">
            CANCEL
          </button>
        </div>
      </motion.div>
    </motion.div>;
}